### ISSUE TITLE
I can't Build It

### ISSUE THREAD

**Issue by Small-Miao** [lkolbly/wows-replays#1]
Do you have release Version. Or Exe version

**Comment by lkolbly** [comment]
Sorry I missed this issue, I'm getting used to the way GitHub handles notifications (in particular, it doesn't email me when people open issues, so it's a different workflow)

Anyway, I have a change to add 0.9.7.0 support coming in the next couple days, so I will upload prebuilt executables and let you know. I assume you are on Windows?

**Comment by Small-Miao** [comment]
Yes, I use windows

When I compile, he will say that there is a front end missing and cannot be downloaded

After I tried to remove it, I managed to compile it

I still hope you can upload a compiled program

**Comment by lkolbly** [comment]
Thanks! I have just published a release with 0.9.7 support [here](https://github.com/lkolbly/wows-replays/releases/tag/v0.9.7) and attached an executable which should work on 64-bit Windows. Let me know if it doesn't work for you, and I'll re-open this issue.
