### ISSUE TITLE
Getting a panic in the decoder on most recent build

### ISSUE THREAD

**Issue by ndsamuelson** [lkolbly/wows-replays#13]
Parsing 20211006_080516_PASC: thread 'main' panicked at 'I64(13600)', parser\src\analyzer\decoder.rs:395:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace.

This is what I get any time I try to survey my 10.9 replays. I spent some time trying to sniff out an obvious fix, but wasn't successful. Could you advise?

**Comment by ndsamuelson** [comment]
for reference, here's the code block:
`                            let avatar = values.get(keys.get("avatarid").unwrap()).unwrap();
                            let username = values.get(keys.get("username").unwrap()).unwrap();
                            let username = std::str::from_utf8(match username {
                                serde_pickle::value::Value::Bytes(u) => u,
                                _ => {
                                    panic!("{:?}", username);
                                }
                            })`

**Comment by lkolbly** [comment]
Thanks for the report! So that section of the code is dealing with the "onArenaStateReceived" packet, which initializes a bunch of stuff including metadata for each player, like username and clan and IDs and stuff. All of the data is tagged per-player (e.g., `0x17` is the ship's initial health), but I don't know where (or if) the data is stored in the .def files, so for now I hardcode which IDs match to which information. Sometimes when they bump the version the mapping changes.

All that is to say, I pushed a commit which passes when I survey my 0.10.9 replays, give that a shot and see if it fixes it.

**Comment by ndsamuelson** [comment]
Here's the output of replayshark.exe dump on a random helena match I had...

H:\SteamLibrary\steamapps\common\World of Warships\replays\0.10.9.0> .\replayshark.exe dump .\20211018_164149_PASC207-Helena_37_Ridge.wowsreplay
{"matchGroup":"cooperative","gameMode":7,"clientVersionFromExe":"0,10,9,4610639","scenarioUiCategoryId":2,"mapDisplayName":"37_Ridge","mapId":21,"clientVersionFromXml":"0,10,9,4610639","weatherParams":{"0":["PCOW005_Evening"],"1":["PCOW010_Rain_Logic","PCOW005_Evening"]},"duration":1200,"gameLogic":"Domination","name":"9x9","scenario":"Domination_3point_Coop","playerID":0,"vehicles":[{"shipId":4077828080,"relation":0,"id":268575140,"name":"NickySams"},{"shipId":3761190704,"relation":2,"id":268506114,"name":":Lee:"},{"shipId":3750672176,"relation":2,"id":268506115,"name":":Warrender:"},{"shipId":3750672176,"relation":1,"id":402756868,"name":"Corsario_II"},{"shipId":3553540080,"relation":2,"id":268506117,"name":":Bouvet:"},{"shipId":4276041712,"relation":2,"id":268506118,"name":":Nakhimov:"},{"shipId":4286494416,"relation":1,"id":402781063,"name":"mariomaritodz"},{"shipId":3762205904,"relation":2,"id":268506120,"name":":Galler:"},{"shipId":4286494416,"relation":2,"id":268506121,"name":":Pakenham:"},{"shipId":4077828080,"relation":2,"id":268506122,"name":":Kolomeitsev:"},{"shipId":4181669328,"relation":2,"id":268506119,"name":":Krabbe:"},{"shipId":3761190704,"relation":1,"id":268464652,"name":"NightStormm"},{"shipId":4181669616,"relation":1,"id":402723311,"name":"Tanky1863"},{"shipId":3761190896,"relation":1,"id":268608786,"name":"Hugetanker"},{"shipId":3762205904,"relation":1,"id":268482422,"name":"todd345"},{"shipId":3553540080,"relation":1,"id":402720921,"name":"21601BSC"},{"shipId":4180621296,"relation":1,"id":268570459,"name":"CaptShreve"},{"shipId":3761190896,"relation":2,"id":268506116,"name":":Cradock:"}],"playersPerTeam":9,"dateTime":"18.10.2021 16:41:49","mapName":"spaces/37_Ridge","playerName":"NickySams","scenarioConfigId":165,"teamsCount":2,"logic":"Domination","playerVehicle":"PASC207-Helena","battleDuration":1200}
{"packet_type":22,"clock":0.0,"payload":{"Unknown":[8,0,0,0,48,44,49,48,44,57,44,48]}}
{"packet_type":16,"clock":0.0,"payload":{"Unknown":[0]}}
{"packet_type":15,"clock":0.0,"payload":{"Unknown":[12,2,43,135,82,200,241,64]}}
{"packet_type":38,"clock":0.0,"payload":{"Unknown":[8,0,0,0]}}
{"packet_type":37,"clock":0.0,"payload":{"Unknown":[239,175,5,0,3,0,0,0,0,0]}}
{"packet_type":16,"clock":0.0,"payload":{"Unknown":[0]}}
{"packet_type":0,"clock":0.0,"payload":{"BasePlayerCreate":{"entity_id":372719,"entity_type":"Avatar","state":[9,0,0,0,80,16,0,0,1,0,0,0,1]}}}
{"packet_type":8,"clock":0.0,"payload":{"EntityMethod":{"entity_id":372719,"method":"onGameRoomStateChanged","args":[[[[11,268608786],[17,true]]],[]]}}}
thread 'main' panicked at 'I64(81900)', parser\src\analyzer\decoder.rs:395:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lkolbly** [comment]
Huh, interesting. decoder.rs:395 doesn't have an unwrap on it (anymore): https://github.com/lkolbly/wows-replays/blob/master/parser/src/analyzer/decoder.rs#L395

it looks like you're running in the WoWS replay directory, maybe the executable in that directory is old?

If not, would it be possible to upload the replay file and I can take a look?

**Comment by ndsamuelson** [comment]
sorry for the delay. Didn't see the notification. I'll fiddle with it later today or tomorrow and see.

**Comment by ndsamuelson** [comment]
Just rebuilt from a fresh clone, I'm testing it out and I'll close this soon if the issue isn't persisting. Most likely it was an ID10T:BAD USER issue. :P

**Comment by ndsamuelson** [comment]
Can confirm that whatever issue there was, has been resolved. Thanks for your time.
