### ISSUE TITLE
Hope to be able to analyze the ship destroyed data

### ISSUE THREAD

**Issue by Small-Miao** [lkolbly/wows-replays#2]
Hope to be able to analyze the ship destroyed data

**Comment by lkolbly** [comment]
Thanks! Release [v0.9.7-1](https://github.com/lkolbly/wows-replays/releases/tag/v0.9.7-1) adds the ShipDestroyed packet, which looks like:
```
{
  "packet_size": 24,
  "packet_type": 8,
  "clock": 385.41638,
  "payload": {
    "ShipDestroyed": {
      "victim": 745158,
      "killer": 745190,
      "death_cause": "Secondaries",
      "unknown": 2
    }
  }
}
```
`victim` and `killer` are ship IDs. `death_cause` has a [variety](https://github.com/lkolbly/wows-replays/blob/master/parser/src/packet.rs#L107) of different possible values.
