### ISSUE TITLE
Determine outcome

### ISSUE THREAD

**Issue by razaqq** [lkolbly/wows-replays#3]
Any idea how to determine which team won from the replay?
There doesnt seem to be a packet for it
The last packet looks smth like this `{"packet_type":4294967295,"clock":0.0,"payload":{"Unknown":[23,175,4,174,97,111,99,111,193,61,140,203,109,187,95,47]}}`

**Comment by lkolbly** [comment]
Hi, thanks for the question!

So I'm not entirely sure what that last packet is. However, it appears that you can determine the winner from the `BattleEnd` packet (`onBattleEnd` RPC method), which looks something like:
```
{"packet_type":8,"clock":775.9111,"payload":{"BattleEnd":{"winning_team":0,"unknown":13}}}
```
where the winning team is as indicated (either 0 or 1), and the "unknown" field is most likely the reason for the victory (i.e., battle time expired, won on points, all ships destroyed, etc. Not entirely sure though)

Note that "0" is not always the player's team. You can determine the player's team from the "teamid" key of the player descriptor in the `OnArenaStateReceived` packet.

I only today added the "teamid" field to that packet, so the `v0.10.7` release should have it.

**Comment by razaqq** [comment]
hmm interesting
the official api has nothing to get a match history, the only other way i found was to read throught the game log files for smth like this
`2021-05-16 00:37:53.064: INFO: [Script] [Avatar] battle finish - Defeat; (, 8930015374123, 280)`

**Comment by lkolbly** [comment]
Yeah, it looks like the replay ends whenever you leave the game, so if you leave the game before it's over then you won't get the `BattleEnd` packet (and therefore whether you won or not). It doesn't look like the end game results data is appended to the replay, either, even if you stay in game long enough for it to pop up.

https://forum.worldofwarships.com/topic/220166-replays-how-to/?tab=comments#comment-5089149 sort of confirms that.
