### ISSUE TITLE
Need some help understanding the format

### ISSUE THREAD

**Issue by razaqq** [lkolbly/wows-replays#7]
I need some help trying to understand the replay format and especially the meaning of some packets.

I get the part of parsing the header meta, decrypting the rest with blowfish, inflating with zlib and so on.

Now you are parsing the rest of the data as packets like this
```c++
struct Packet
{
  uint32_t size;
  uint32_t type;
  float clock;
  std::byte raw[size];
};
```

depending on the type you now parse the `raw` rest into the payload of the packet, so for example a `BasePlayerCreate` packet would look like this

```c++
struct BasePlayerCreatePacket
{
  uint32_t size;
  uint32_t type;
  float clock;
  struct
  {
    uint32_t entityId;
    uint16_t entityType;
    std::byte state[size - sizeof(entityId) - sizeof(entityType)];
  } payload;
};
```

what are `EntityMethod`, `EntityProperty`, `PropertyUpdate`? whats the difference between `BasePlayerCreate` and `CellPlayerCreate`?

**Comment by lkolbly** [comment]
> whats the difference between BasePlayerCreate and CellPlayerCreate?

If you find out, you're going to have to tell me - I have no idea.

> what are EntityMethod, EntityProperty, PropertyUpdate?

So at a high level, the server and client communicate via an RPC-like interface. Objects (ships, avatars, etc.) exist, and methods are called on them. Additionally, these objects can have properties associated with them (for example, health). I'm extracting the different possible methods and properties from the files in the `versions/` folder, [here](https://github.com/lkolbly/wows-replays/blob/master/versions/0.10.7/scripts/entity_defs/Avatar.def). For example, this packet that I just dumped from a replay:
```
{"packet_type":8,"clock":0.0,"payload":{"EntityMethod":{"entity_id":509883,"method":"onConnected","args":[[128,2,40,73,52,50,57,50,56,53,52,52,56,48,10,75,0,125,125,116,113,1,46]]}}}
```
corresponds, I think, to [this method](https://github.com/lkolbly/wows-replays/blob/master/versions/0.10.7/scripts/entity_defs/Avatar.def#L154).

Additionally, there are various properties associated with objects. Additionally, properties have a somewhat complicated (Python-dictionary-like) structure. For example, take a look at this `PropertyUpdate` packet:
```
{"packet_type":34,"clock":39.368,"payload":{"PropertyUpdate":{"entity_id":452223,"property":"state","update_cmd":{"levels":[{"DictKey":"missions"},{"DictKey":"teamsScore"},{"ArrayIndex":0}],"action":{"SetKey":{"key":"score","value":304}}}}}}
```
The "levels" part is specifying the Python "path". The above packet would be equivalent to a Python call like this:
```
someObject["missions"]["teamsScore"][0]["score"] = 304
```
The `PropertyUpdate` packet allows the game to update just one value in the property, without updating the entire everything. The full property state for that object, 452223, is:
```
{"packet_type":5,"clock":0.0,"payload":{"EntityCreate":{"entity_id":452223,"entity_type":"BattleLogic","vehicle_id":4451,"space_id":0,"position_x":0.0,"position_y":0.0,"position_z":0.0,"dir_x":0.0,"dir_y":0.0,"dir_z":0.0,"unknown":324,"props":{"teams":{"friendlyFire":0,"detonation":1,"teams":[{"friendlyFire":0,"teamId":0,"detonation":1},{"detonation":1,"friendlyFire":0,"teamId":1}]},"battleType":188,"timeLeft":0,"state":{"successStoryProgress":[],"uiInfo":{"miniMapType":0},"clientAnimations":{"ids":[],"targetType":0},"sounds":[],"drop":null,"effects":[],"entityStates":[],"tasks":[],"controlPoints":[{"position":[-342.0,0.0],"bothInside":0,"controlPointType":1,"isEnabled":1,"innerRadius":0.0,"neutralProgress":0.0,"buoy_modelID":4290944628,"invaderTeam":-1,"hasInvaders":0,"captureTime":60.0,"isVisible":1,"teamId":-1,"progress":0.0,"nextControlPoint":-1,"radius":140.0,"timerName":[]},{"bothInside":0,"captureTime":60.0,"nextControlPoint":-1,"innerRadius":0.0,"controlPointType":1,"progress":0.0,"buoy_modelID":4290944628,"radius":110.0,"neutralProgress":0.0,"hasInvaders":0,"isEnabled":1,"position":[0.0,193.0],"invaderTeam":-1,"timerName":[],"teamId":0,"isVisible":1},{"position":[0.0,-193.0],"innerRadius":0.0,"progress":0.0,"isEnabled":1,"isVisible":1,"neutralProgress":0.0,"hasInvaders":0,"radius":110.0,"nextControlPoint":-1,"buoy_modelID":4290944628,"bothInside":0,"invaderTeam":-1,"controlPointType":1,"captureTime":60.0,"timerName":[],"teamId":1},{"teamId":-1,"isEnabled":1,"controlPointType":1,"captureTime":60.0,"nextControlPoint":-1,"bothInside":0,"buoy_modelID":4290944628,"innerRadius":0.0,"timerName":[],"radius":140.0,"isVisible":1,"invaderTeam":-1,"hasInvaders":0,"progress":0.0,"neutralProgress":0.0,"position":[300.0,0.0]}],"expectedActions":null,"minefields":[],"attentionMarkers":[],"entities":[],"diplomacy":null,"resources":[],"keyObjects":[],"missions":{"kill":[{"reward":30,"penalty":45,"shipType":[68,101,115,116,114,111,121,101,114]},{"penalty":50,"shipType":[67,114,117,105,115,101,114],"reward":35},{"shipType":[66,97,116,116,108,101,115,104,105,112],"penalty":60,"reward":40},{"reward":45,"penalty":65,"shipType":[65,105,114,67,97,114,114,105,101,114]}],"capture":[],"suppress":[],"teamsScore":[{"score":300,"teamId":0},{"teamId":1,"score":300}],"hold":[{"period":9,"cpIndices":[1,2,0,3],"reward":4,"penalty":0}],"teamLoseScore":0,"teamWinScore":1000},"weather":{"mainWeather":0,"globalWeather":{"param":4291086256,"item":null,"notification":null},"localWeather":[]}},"prerequisiteData":{"weather":[],"squadrons":[],"ships":[],"effects":[]},"mapBorder":{"position":[0.0,0.0,0.0],"paramsId":4289513392},"duration":0,"battleStage":2,"debugText":[]}}}}
```
which is a lot to send every time the score updates.

For _some_ packets, mostly just ones I find particularly interesting (or that people ask to have called out), I do a little bit of extra heavy lifting to convert the above method/property calls into something a little more useful. For example, the `ShipDestroyed` packet is, internally, just an `EntityMethod`. But I prettied it up and added labels to the numbers so it's easier for human consumption:
```
{"packet_type":8,"clock":168.23236,"payload":{"ShipDestroyed":{"killer":452259,"victim":452255,"cause":"Fire"}}}
```
All of this "prettying up" code happens inside [decoder.rs](https://github.com/lkolbly/wows-replays/blob/master/parser/src/analyzer/decoder.rs).

**Comment by razaqq** [comment]
Thanks for the detailed answers, i was mostly right my assumptions.
So if you wanted to recreate the game you could create some Entity class and invoke methods on it depending on the rpc calls.

One more quesion: Where is the info from `versions/` coming from? Is that somewhere in game files or do you get that by reverse engineering the game binary?

**Comment by lkolbly** [comment]
> So if you wanted to recreate the game you could create some Entity class and invoke methods on it depending on the rpc calls.

Yeah pretty much.

I'm getting the `versions/` data from the `wowsunpack` tool in the `scripts/` directory. I've actually mostly reverse-engineered the .idx/.pkg file formats, so soonish I'll be adding a tool to this repo which can extract data from those. (also, if we're being honest, I'm copying a lot of the data from [here](https://github.com/Monstrofil/replays_unpack/tree/master/replay_unpack/clients/wows/versions))
